server:
  port: 9002
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kumoya/config-test/application-config
          username: kumoya
          password: db99b,k22to1981
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka