server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  cloud:
    config:
      name: employee
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: jdbc:mysql://192.168.1.101:3307/mydb
    username: root
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
