server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: employee
  datasource:
    url: jdbc:mysql://192.168.0.101:3307/mydb
    username: root
    password: mypassword
  mvc:
    pathmatch:
          matching-strategy: ant_path_matcher    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
